'use strict';
window.Neural=(()=>{
 let timer=null,frame=null,resize=null,controller=null,lastSection=null,introTimer=null,welcomeFocus=null;
 const inertBefore=new Map();
 const media=matchMedia('(prefers-reduced-motion: reduce)'),introKey=DALI_CONFIG.storageKey+'-welcome-v4';
 const reduced=()=>media.matches||Store.get()?.preferences.motion==='reduced';
 function clock(date=new Date()){return {time:new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',hour:'numeric',minute:'2-digit',hour12:true}).format(date),date:new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(date)};}
 function tick(){const v=clock(),time=document.getElementById('global-time'),date=document.getElementById('global-date');if(time)time.textContent=v.time;if(date)date.textContent=v.date;V2App.clock();if(window.Agenda)Agenda.clock();if(window.DaliCore)DaliCore.refresh();}
 function dispose(){if(window.DaliCore)DaliCore.dispose();if(timer!==null)clearInterval(timer);timer=null;if(frame!==null)cancelAnimationFrame(frame);frame=null;resize?.disconnect();resize=null;controller?.abort();controller=null;if(window.NeuralCharts)NeuralCharts.destroy();}
 function orb(){if(reduced()||document.hidden||Store.get().preferences.motionPaused)return;const canvas=document.getElementById('neural-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;let width=0,height=0,pointer=0;const count=Store.get().preferences.motion==='full'?22:12;controller=new AbortController();canvas.parentElement.addEventListener('pointermove',ev=>{pointer=(ev.offsetX/Math.max(width,1)-.5)*.15;},{signal:controller.signal});resize=new ResizeObserver(()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);width=rect.width;height=rect.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);});resize.observe(canvas);let last=0;function draw(time){if(document.hidden||!canvas.isConnected){frame=null;return;}frame=requestAnimationFrame(draw);if(time-last<40)return;last=time;ctx.clearRect(0,0,width,height);const radius=Math.min(width,height)*.35,key=document.documentElement.dataset.theme+':'+document.getElementById('neural-home-hero')?.dataset.coreState;if(draw.paletteKey!==key){const palette=getComputedStyle(canvas);draw.ray=palette.getPropertyValue('--core-ray').trim();draw.particle=palette.getPropertyValue('--core-particle').trim();draw.paletteKey=key;}ctx.strokeStyle=draw.ray;ctx.fillStyle=draw.particle;ctx.lineWidth=.6;for(let n=0;n<count;n++){const a=n/count*Math.PI*2+time*.000025+pointer,x=width/2+Math.cos(a)*radius,y=height/2+Math.sin(a)*radius*.68;ctx.beginPath();ctx.moveTo(width/2,height/2);ctx.lineTo(x,y);ctx.stroke();ctx.beginPath();ctx.arc(x,y,n%3===0?2:1,0,Math.PI*2);ctx.fill();}}frame=requestAnimationFrame(draw);}
 function dismiss(){clearTimeout(introTimer);introTimer=null;document.getElementById('welcome-scene')?.remove();for(const [el,previous] of inertBefore)el.inert=previous;inertBefore.clear();if(welcomeFocus?.isConnected)welcomeFocus.focus({preventScroll:true});welcomeFocus=null;document.documentElement.classList.add('neural-ready');}
 function welcome(force=false){let seen=false;try{seen=sessionStorage.getItem(introKey)==='seen';if(!force&&seen){dismiss();return;}sessionStorage.setItem(introKey,'seen');}catch{if(!force&&window.__daliWelcomeSeen){dismiss();return;}}window.__daliWelcomeSeen=true;dismiss();const scene=document.createElement('section');scene.id='welcome-scene';scene.className='welcome-scene';scene.setAttribute('aria-label','Bienvenida a tu CRM personal');scene.setAttribute('role','dialog');scene.setAttribute('aria-modal','true');welcomeFocus=document.activeElement;for(const el of document.body.children){if(['SCRIPT','LINK'].includes(el.tagName))continue;inertBefore.set(el,el.inert);el.inert=true;}scene.innerHTML='<div class="welcome-line"></div><h2>WELCOME, BOSS</h2><p>Bienvenido, jefe.</p><button type="button" class="button" id="welcome-skip">Omitir</button>';document.body.append(scene);document.documentElement.classList.remove('neural-ready');const skip=document.getElementById('welcome-skip');skip.onclick=dismiss;skip.focus({preventScroll:true});scene.addEventListener('keydown',ev=>{if(ev.key==='Tab'){ev.preventDefault();skip.focus();}if(ev.key==='Escape'){ev.preventDefault();dismiss();}});introTimer=setTimeout(dismiss,reduced()?250:1600);}
 function beforeRender(){dispose();}
 function afterRender(){document.body.dataset.module=UI.section;document.documentElement.dataset.motion=reduced()?'reduced':Store.get().preferences.motion||'subtle';document.documentElement.dataset.paused=String(!!Store.get().preferences.motionPaused);tick();if(timer===null&&!document.hidden)timer=setInterval(tick,1000);const main=document.getElementById('main-content');if(lastSection!==UI.section&&!reduced()){main.classList.remove('neural-view-enter');void main.offsetWidth;main.classList.add('neural-view-enter');}lastSection=UI.section;if(UI.section!=='inicio'){const heading=main.querySelector('.page-heading'),section=DALI_CONFIG.sections.find(s=>s.route===UI.section);if(heading&&!heading.querySelector('.neural-module-art'))heading.insertAdjacentHTML('beforeend','<span class="neural-module-art" aria-hidden="true">'+Views.icon(section.icon)+'</span>');}if(UI.section==='configuracion'){main.insertAdjacentHTML('beforeend',`<section class="panel detail-card" id="neural-preferences"><h2>Tu experiencia DALI</h2><p>Movimiento adaptado a tus preferencias y a las de tu dispositivo.</p><div class="toolbar"><label>Intensidad<select class="select" id="motion-preference"><option value="full">Completa</option><option value="subtle">Sutil</option><option value="reduced">Reducida</option></select></label>${Views.button('Repetir entrada','v4-welcome')}${Views.button(Store.get().preferences.motionPaused?'Reanudar movimiento':'Pausar movimiento','v4-pause')}</div><p>Reloj de Ciudad Guzmán · America/Mexico_City · 12 horas.</p></section>`);const select=document.getElementById('motion-preference');select.value=Store.get().preferences.motion||'subtle';select.onchange=()=>{Store.save(s=>s.preferences.motion=select.value);App.render();};}if(window.NeuralModules)NeuralModules.decorate();if(window.NeuralCharts)NeuralCharts.mount();if(window.DaliCore)DaliCore.mount();orb();if(!window.__neuralBoot){window.__neuralBoot=true;welcome();}else if(!document.getElementById('welcome-scene'))document.documentElement.classList.add('neural-ready');App.icons();}
 function action(el){if(el.dataset.action==='v4-welcome'){welcome(true);return;}if(el.dataset.action==='v4-pause'){Store.save(s=>s.preferences.motionPaused=!s.preferences.motionPaused);App.render();return;}if(window.NeuralLinks&&el.dataset.action.startsWith('v4-link'))return NeuralLinks.action(el);}
 document.addEventListener('visibilitychange',()=>{dispose();document.documentElement.dataset.visibility=document.hidden?'hidden':'visible';if(!document.hidden&&window.DALI_READY){tick();timer=setInterval(tick,1000);orb();}});media.addEventListener('change',()=>{if(window.DALI_READY)App.render();});
 return {beforeRender,afterRender,action,clock,reduced,welcome,dismiss,dispose,stats:()=>({raf:frame!==null,clockTimers:timer===null?0:1})};
})();
